packages:
  - "artifacts/*"

allowBuilds:
  esbuild: set this to true or false

catalog:
  "@replit/vite-plugin-cartographer": "0.6.1"
  "@replit/vite-plugin-dev-banner": "0.1.2"
  "@replit/vite-plugin-runtime-error-modal": "0.0.6"
  "@tailwindcss/vite": "4.1.4"
  "@tanstack/react-query": "5.74.0"
  "@types/node": "22.13.10"
  "@types/react": "19.0.12"
  "@types/react-dom": "19.0.4"
  "@vitejs/plugin-react": "4.3.4"
  class-variance-authority: "0.7.1"
  clsx: "2.1.1"
  framer-motion: "12.6.3"
  lucide-react: "0.475.0"
  react: "19.0.0"
  react-dom: "19.0.0"
  tailwind-merge: "3.0.2"
  tailwindcss: "4.1.4"
  vite: "6.2.5"
  zod: "3.24.2"
